---

- name: install nginx with apt
  become: yes
  apt:
    name:
      - nginx
    state: latest

- name: user access to web root
  become: yes
  file:
    path: '/var/www/html'
    recurse: yes
    owner: '{{nginx_document_root_user}}'
    group: '{{nginx_document_root_group}}'
